name: Build and Merge Develop into Master

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Asegura que todas las ramas se descarguen

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Cambia a la versión de Node.js que uses

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Cambia esto según tu comando de build

      - name: Merge develop into master
        if: success()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout master || git checkout -b master # Asegura que la rama master esté presente
          git merge develop
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} master
