name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21" # Cambia a la versión de Node.js que uses

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # Cambia esto según tu comando de build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH and copy files
        env:
          SSH_USER: ${{ secrets.HOSTINGER_USER }}
          SSH_HOST: ${{ secrets.HOSTINGER_IP }}
          SSH_PORT: ${{ secrets.HOSTINGER_PORT }}
          TARGET_DIR: ${{ secrets.HOSTINGER_TARGET_DIR }}
          HOSTINGER_PASS: ${{ secrets.HOSTINGER_PASS }}
      run: |
        sshpass -p "$HOSTINGER_PASS" scp -P $SSH_PORT -o StrictHostKeyChecking=no -r ./build/* $SSH_USER@$SSH_HOST:$TARGET_DIR